Tms:
  Consent:
    config:
      translations:
        de:
          cloudflare:
            description: 'Schützt uns vor Angreifern und hilft dabei unsere Inhalte weltweit schnell zu verteilen.'

        en:
          cloudflare:
            description: 'Protects us from attackers and helps to distribute our content quickly worldwide.'

      services:
        cloudflare:
          enabled: false

          # -----------------------------------------------------------------
          # Klaro! Config
          # -----------------------------------------------------------------
          klaro:
            name: cloudflare
            title: 'Cloudflare'
            purposes: ['performance']
            required: true
