Tms:
  Consent:
    config:
      translations:
        de:
          youtube:
            description: 'Erlaube eingebettete Youtube Videos auf dieser Website'

        en:
          youtube:
            description: 'Allow embedded Youtube videos on this site'

      apps:
        youtube:
          enabled: false

          # -----------------------------------------------------------------
          # Klaro! Config
          # -----------------------------------------------------------------
          klaro:
            name: youtube
            default: false
            title: 'Youtube'
            purposes: ['functionality']
