Tms:
  Consent:
    config:
      translations:
        en:
          consentNotice:
            learnMore: 'Customize'

          acceptAll: 'Accept all applications'
          acceptSelected: 'Accept selected'

          purposes:
            performance: 'Security & Performance'
            functionality: 'Functionality'
            analytics: 'Analytics'
            targeting: 'Targeting and Advertising'
