Tms:
  Consent:
    config:
      translations:
        de:
          consentNotice:
            learnMore: 'Einstellungen anpassen'

          acceptAll: 'Alle akzeptieren'
          acceptSelected: 'Auswahl speichern'

          purposes:
            performance: 'Sicherheit & Performance'
            functionality: 'Funktionalität'
            analytics: 'Statistiken'
            targeting: 'Anzeigen von Werbung'
