Tms:
  Consent:
    config:
      translations:
        de:
          # See default DE translation - https://github.com/kiprotect/klaro/blob/master/src/translations/de.yml
          consentNotice:
            learnMore: 'Anpassen'

          decline: 'Ablehnen'
          ok: 'Alle Dienste akzeptieren'
          acceptSelected: 'Auswahl speichern'

          purposes:
            performance:
              title: 'Sicherheit und Performance'
              description: ''
            functionality:
              title: 'Funktionalität'
              description: ''
            content:
              title: 'Externe Inhalte'
              description: ''
            analytics:
              title: 'Webanalyse'
              description: ''
            marketing:
              title: 'Marketing'
              description: ''
