Tms:
  Consent:
    config:
      translations:
        de:
          matomo:
            description: 'Ermöglicht uns eine Auswertung der Website Nutzung (z.B. Seitenaufrufe, Kanäle, Endgeräte, Bildschirmauflösungen, etc.)'

        en:
          matomo:
            description: 'Allows us to analyse website usage (e.g. pageviews, channels, devices, screen resolutions, etc.)'

      services:
        matomo:
          # Each app must include the 'enabled' key and should be disabled
          # by default within this package
          enabled: false

          # -----------------------------------------------------------------
          # Klaro! Config
          # -----------------------------------------------------------------
          klaro:
            name: matomo

            # If "default" is set to true, the service will be enabled by default
            # Overwrites global "default" setting.
            # We recommend leaving this to "false" for services that collect
            # personal information.
            default: false

            # The title of you app as listed in the consent modal.
            title: 'Matomo / Piwik'

            # The purpose(s) of this app. Will be listed on the consent notice.
            # Do not forget to add translations for all purposes you list here.
            purposes: ['analytics']

            # A list of regex expressions or strings giving the names of
            # cookies set by this app. If the user withdraws consent for a
            # given app, Klaro will then automatically delete all matching
            # cookies.
            # You can also explicitly provide a path and a domain for
            # a given cookie. This is necessary if you have services that
            # set cookies for a path that is not "/" or a domain that
            # is not the current domain. If you do not set these values
            # properly, the cookie can't be deleted by Klaro
            # (there is no way to access the path or domain of a cookie in JS)
            cookies: [/^_pk_/, 'piwik_ignore']

            # If "required" is set to true, Klaro will not allow this app to
            # be disabled by the user.
            required: false

            # If "optOut" is set to true, Klaro will load this app even before
            # the user gave explicit consent.
            # We recommend always leaving this "false".
            optOut: false
