Tms:
  Consent:
    config:
      translations:
        en:
          # See default EN translation - https://github.com/kiprotect/klaro/blob/master/src/translations/en.yml
          consentNotice:
            learnMore: 'Customize'

          decline: 'Decline'
          ok: 'Accept all services'
          acceptSelected: 'Accept selected'

          service:
            purpose: Purpose
            purposes: Purposes

          purposes:
            performance:
              title: 'Security and Performance'
              description: ''
            functionality:
              title: 'Functionality'
              description: ''
            content:
              title: 'External Content'
              description: ''
            analytics:
              title: 'Analytics'
              description: ''
            marketing:
              title: 'Marketing'
              description: ''
