Tms:
  Consent:
    config:
      translations:
        de:
          googleMaps:
            description: 'Erlaube eingebettete Google Maps auf dieser Website'

        en:
          googleMaps:
            description: 'Allow embedded Google Maps on this site'

      apps:
        googleMaps:
          enabled: false

          # -----------------------------------------------------------------
          # Klaro! Config
          # -----------------------------------------------------------------
          klaro:
            name: googleMaps
            default: false
            title: 'Google Maps'
            purposes: ['functionality']
