Tms:
  Consent:
    config:
      translations:
        de:
          matomo:
            description: 'Sammeln von Besucherstatistiken'

      apps:
        matomo:
          # Each app must include the 'enabled' key and should be disabled
          # by default within this package
          enabled: false

          # Search & replace the resulting HTML by these patterns
          modifyHtml:
            - pattern: '/<script(.*?)type="text\/javascript"(.*?)>([\s\S]*?)<\/script>/'
              replacement: '<script$1type="opt-in" data-name="matomo" data-type="text/javascript"$2>$3</script>'

          # -----------------------------------------------------------------
          # Klaro! Config
          # -----------------------------------------------------------------
          klaro:
            name: matomo

            # If "default" is set to true, the app will be enabled by default
            # Overwrites global "default" setting.
            # We recommend leaving this to "false" for apps that collect
            # personal information.
            default: true

            # The title of you app as listed in the consent modal.
            title: 'Matomo/Piwik'

            # The purpose(s) of this app. Will be listed on the consent notice.
            # Do not forget to add translations for all purposes you list here.
            purposes: ['tracking']

            # A list of regex expressions or strings giving the names of
            # cookies set by this app. If the user withdraws consent for a
            # given app, Klaro will then automatically delete all matching
            # cookies.
            # You can also explicitly provide a path and a domain for
            # a given cookie. This is necessary if you have apps that
            # set cookies for a path that is not "/" or a domain that
            # is not the current domain. If you do not set these values
            # properly, the cookie can't be deleted by Klaro
            # (there is no way to access the path or domain of a cookie in JS)
            cookies: [/^_pk_/, 'piwik_ignore']

            # If "required" is set to true, Klaro will not allow this app to
            # be disabled by the user.
            required: false

            # If "optOut" is set to true, Klaro will load this app even before
            # the user gave explicit consent.
            # We recommend always leaving this "false".
            optOut: false
