Neos:
  Fusion:
    defaultContext:
      'Tms.Consent.Klaro': 'Tms\Consent\Eel\Helper\KlaroHelper'
  Neos:
    fusion:
      autoInclude:
        'Tms.Consent': true

Tms:
  Consent:
    enabled: true

    # Disable includes if you use your own or want to add them to your favorite build tool
    autoInclude:
      config: true
      scripts: true
      styles: true


    enableStickyConsentSettingsButton: true

    config:
      # The privacy policy uri can be specified by node type, path, identifier or simply an absolute/relative link
      # privacyPolicy: 'Vendor.Site:Document.PrivacyPolicy'
      # privacyPolicy: '#4999814e-61c2-4ce1-ab46-c1145f2285d7'
      # privacyPolicy: '/privacy-policy.html'
      privacyPolicy: ''

      # Find all general translations in setting files, separated by language - see 'Settings.Translations.De.yaml'
      # App related translations should be within each app setting file - see 'Settings.Consent.Matomo.yaml'
      translations: []

      # Find individual service configurations in separated setting files
      services: []
